### ISSUE TITLE
Confused about this

### ISSUE THREAD

**Issue by Robinfr** [CreateJS/Combined#10]
This confuses me a bit. I came here after getting the email about the NPM package now being available on NPM. But the README makes me think that this is not a true NPM package which you can just install and use in your project, but rather install, install more dependencies, build everything, still have to mess around with a bunch of settings, and then finally be able to use it.

Please correct me if I'm wrong.

**Comment by lannymcnie** [comment]
You are partly correct. You can install and use as-is, however the repository has the tools to build CreateJS combined versions as well.

**Comment by Robinfr** [comment]
So anyone would be able to do the following to use this in their setup by doing (just taking a basic Webpack + Babel setup):

1. Running `npm install createjs --save`
2. Importing createjs in their project: `import createjs from 'createjs';`
3. Use `createjs` as normal

If that's correct, it's not very clear from the README at the moment.

**Comment by lannymcnie** [comment]
Yeah, you are right. I was in the process of updating the readme, which was initially only intended for folks building with the repository. I included your steps above :)

**Comment by lannymcnie** [comment]
Sorry, to clarify, you can't use createjs with imports yet (no module support yet), so its just a download and use situation

**Comment by Robinfr** [comment]
Ah that's too bad. Since it means we still need to apply some tricks to get it running with Webpack for example. It's definitely a step in the right direction however to have an official package! Is there any ETA on when module support will be added?

**Comment by lannymcnie** [comment]
We have an ES6 branch already working for EaselJS that just needs to be caught up to the latest (it is a bit out of date). Then we plan on porting the existing libs to ES6, and our plan fully covers all the existing frameworks. Hopefully before the end of the year.

**Comment by Robinfr** [comment]
Alright, I'll be looking forward to seeing the result of that. I'll close this issue since it's clear now what the goal is of this NPM package. Thanks for the answers!
