### ISSUE TITLE
Is a new Combined Version possible?

### ISSUE THREAD

**Issue by clark-stevenson** [CreateJS/Combined#14]
Hey Guys 👍 

I was wondering if it would be possible to create a new Combined build? 

My issue was https://github.com/CreateJS/TweenJS/issues/101 

At some point I reformatted, and forgot about my local fix.  Anyway no big deal, I am sure nothing is stopping me using the modular libraries if I need to.  Just wondered. 

thanks

**Comment by lannymcnie** [comment]
I am happy to make a combined build for you (attached). Pushing to our CDN requires a bunch of cross-library testing, and there aren't really enough recent changes to justify a new dot-release at this time.

You can always use the combined github library any time to generate your own builds: https://github.com/CreateJS/Combined

You have to also check out the other repositories, the README should provide adequate instructions.

[createjs-2018.07.03.zip](https://github.com/CreateJS/Combined/files/2159518/createjs-2018.07.03.zip)

**Comment by clark-stevenson** [comment]
@lannymcnie  Thank you! I was literally about to close this as setting a `maxDelta` solves my immediate issue.  But your build is appreciated. I have no idea how I missed the instructions.

**Comment by lannymcnie** [comment]
Glad to hear. Always happy to help!
