### ISSUE TITLE
Create Task for CDN builds

### ISSUE THREAD

**Issue by lannymcnie** [CreateJS/Combined#3]
It would be super handy to have a task that copied the necessary files for the CDN to a folder:
1. The `.min` version of each lib, including MovieClip
2. The `.min` and `.combined` versions of the bundled library
3. The CDN index (would require a manual update of the CDN page)

This should not be part of the `build` task, but rather a separate one, which assumes the CDN page and libraries have been built.

**Comment by wdamien** [comment]
Fixed, and also integrated a proper build process for the index.html file.
