### ISSUE TITLE
Include SpriteStage & SpriteContainer in minified files on CDN

### ISSUE THREAD

**Issue by ghost** [CreateJS/Combined#4]
Hi

this article mentioned that spriteStage and spriteContainer would soon be included in the minified version. That way we can load the entire thing from CDN.

thanks

**Comment by lannymcnie** [comment]
These classes are currently not included on the CDN. Can you post the link to the article you are referring to? We may include the classes in future releases.

**Comment by ghost** [comment]
sorry i thought i had added a link to the article - http://blog.createjs.com/webgl-support-easeljs/

**Comment by lannymcnie** [comment]
This is now outdated, since SpriteContainer and SpriteStage are deprecated and removed -- and StageGL is part of the minified build.
