### ISSUE TITLE
CDN - and process for latest bundled min file

### ISSUE THREAD

**Issue by danzen** [CreateJS/Combined#8]
Hi folks, as you might know, I do the ZIM framework that is powered by CreateJS and have been using the CDN link: https://code.createjs.com/createjs-2015.11.26.min.js  I have a lot of students and beginners using ZIM - and it would be nice if they did not have to go through the grunt process to get a combined min file for the CreateJS modules - yet it would also be good to have the updates from the last year and a half.  I suppose that this is a request to have the CDN updated ;-).  

Barring that, perhaps you could post some of the bundled min files here as you go (if you have not already - maybe I missed them).  And... barring that, could you please confirm that the instructions posted in the readme are current.  I am not sure what these lines mean... maybe a few more details - thanks!

Install all the dependencies for this project.
npm install
Make sure you have the latest of all the createjs libraries.
Install the dependencies in the build directories for each project, ie EaselJS/build
npm install

I know that you have some cool things related to your CDN - like the caching with Interactive Advertising Bureau, Adobe Animate tie-in etc.  So perhaps updating often is a challenge. 

Thanks a million - and as always, great job and love you guys.

**Comment by lannymcnie** [comment]
We have pushed a new tagged version. Enjoy!

We will likely not keep the combined version up-to-date, since the libraries get their own updates at an inconsistent rate. That said, we shouldn't be having 2 years between builds :)
